name : Test All Program

on : 
  push:
    branches : [ master ]

jobs :
  build :
    name : Testing Phase
    runs-on : ubuntu-18.04
    steps :
      - name : Checkout
        uses : actions/checkout@v2
      - name : Set up Python 2.7
        uses : actions/setup-python@v2
        with :
          python-version: 2.7
      - name : Install Python dependencies
        run : |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name : pylint increasing_arr
        run : |
          echo $PWD
          cd python
          pylint increasing_arr.py
      - name : Lint with pylint
        run : |
            echo $PWD
            cd python
            pylint --exit-zero increasing_arr.py
            pylint --exit-zero missing_num.py
            pylint --exit-zero repetitions.py
            pylint --exit-zero test_all.py
            pylint --exit-zero weird_algo.py
           
      - name  : Run python tests
        run : |
          echo $PWD
          pytest
          cd ..
      - name : Setup GTest
        run : |
          sudo apt-get install libgtest-dev
          sudo apt-get install cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib
          cd /home/runner/work/Personal_github_ActionTesting/Personal_github_ActionTesting
      - name : Run G tests
        run : |
          cd cpp
          g++ tester.cpp -o tester_exec -lgtest -lpthread
          ./tester_exec
